os: windows      # Windows Server, version 1803
language: shell  # 'language: python' is not yet supported on Windows

before_install:
  - choco install python --version 3.8.0
  - python -m pip install --upgrade pip
env: PATH=/c/Python38:/c/Python38/Scripts:$PATH
install:
  - pip3 install --upgrade pip
  - pip3 install pyinstaller
  - pip3 install -r requirements.txt

script:
  - pyinstaller --noconfirm --clean --onefile --icon resources\logo_icon.ico ctn_onboarding_automation.py
  - ls -l dist