os: windows
language: shell
before_install:
  - openssl aes-256-cbc -K $encrypted_c5fd3201494e_key -iv $encrypted_c5fd3201494e_iv
    -in config.json.enc -out config.json -d
  - choco install python --version 3.8.0
  - python -m pip install --upgrade pip
env: PATH=/c/Python38:/c/Python38/Scripts:$PATH
install:
  - pip3 install --upgrade pip
  - pip3 install pyinstaller
  - pip3 install -r requirements.txt
script:
  - pyinstaller --noconfirm --clean --onefile --add-data 'config.json;.' --icon 'resources\logo_icon.ico' ctn_onboarding_automation.py
